cache:
    - apt
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y build-essential python python-dev python2.7 python2.7-dev doxygen libblas-dev liblapack-dev gfortran git make flex bison libssl-dev libedit-dev python-scipy
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update -q && sudo apt-get install -y gcc-4.7 g++-4.7 && sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 20 && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.7 20 && sudo update-alternatives --config gcc && sudo update-alternatives --config g++
    - sudo add-apt-repository -y ppa:boost-latest/ppa && sudo apt-get update -q && sudo apt-get install -y boost1.55
    - sudo add-apt-repository -y ppa:kalakris/cmake && sudo apt-get update -q && sudo apt-get install -y cmake
    - sudo add-apt-repository -y ppa:chris-lea/python-numpy && sudo apt-get update -q && sudo apt-get install -y python-numpy
    - sudo pip install -r requirements.txt
    - sudo pip install flake8 flake8-import-order pep8-naming flake8-docstrings
install:
    - sudo python setup.py install
script:
    - testify -v moe.tests
    - flake8 --ignore=E501,E126,E123,I101,N806 moe
    - pep257 moe
    - python docs/cpp_rst_maker.py && doxygen docs/doxygen_config && sphinx-apidoc -f -o docs moe && sphinx-build -b html docs docs/_build/html
