package:
  name: cornell_moe2
  version: "0.1.1"

source:
  path: ../../

build:
  number: 1

requirements:
  build:
    - python
    - emcee
    - setuptools
    - boost=1.65.1
    - numpy
    - future
    - scipy
  
  run:
    - python
    - boost=1.65.1
    - setuptools
    - numpy
    - scipy
    - emcee
    - future

test:
  # Python imports
  imports:
    - moe
